version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:18.19.0 # Use Node.js for Jest testing
    working_directory: ~/project

jobs:
  test:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Run tests
          command: npm test

workflows:
  version: 2
  test-workflow:
    jobs:
      - test
